version: '3.7'

services:
    nginx:
        container_name: "nginx"
        build:
            context: ./infra/nginx
        volumes:
            - ${APP_FOLDER}:/var/www
            - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
            - mongo-express
        ports:
            - "80:80"

    php:
        container_name: "php-fpm"
        build:
            context: ./infra/php
        environment:
            - APP_ENV=${APP_ENV}
            - APP_SECRET=${APP_SECRET}
        volumes:
            - ${APP_FOLDER}:/var/www

    mongodb:
        image : mongo
        container_name: mongodb
        environment:
            - MONGO_INITDB_ROOT_USERNAME=dardael
            - MONGO_INITDB_ROOT_PASSWORD=aty30ITE
        volumes:
            - mongodb-data:/data/db
        ports:
            - 27017:27017
        restart: unless-stopped

    mongo-express:
        image: mongo-express
        container_name: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
            - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
            - ME_CONFIG_MONGODB_ADMINUSERNAME=dardael
            - ME_CONFIG_MONGODB_ADMINPASSWORD=aty30ITE
            - ME_CONFIG_BASICAUTH_USERNAME=admin
            - ME_CONFIG_BASICAUTH_PASSWORD=aty30ITE
        volumes:
            - mongodb-data:/data/db
        depends_on:
            - mongodb
        ports:
            - 8081:8081
        restart: unless-stopped
            
volumes:
    mongodb-data:
        name: mongodb-data
